// Todos los símbolos de monedas del mundo, ordenados alfabéticamente.
export const SYMBOLS_COMPLETO = [
    'AED',
    'AFN',
    'ALL',
    'AMD',
    'ANG',
    'AOA',
    'ARS',
    'AUD',
    'AWG',
    'AZN',
    'BAM',
    'BBD',
    'BDT',
    'BGN',
    'BHD',
    'BIF',
    'BMD',
    'BND',
    'BOB',
    'BRL',
    'BSD',
    'BTC',
    'BTN',
    'BWP',
    'BYN',
    'BYR',
    'BZD',
    'CAD',
    'CDF',
    'CHF',
    'CLF',
    'CLP',
    'CNY',
    'COP',
    'CRC',
    'CUC',
    'CUP',
    'CVE',
    'CZK',
    'DJF',
    'DKK',
    'DOP',
    'DZD',
    'EGP',
    'ERN',
    'ETB',
    'EUR',
    'FJD',
    'FKP',
    'GBP',
    'GEL',
    'GGP',
    'GHS',
    'GIP',
    'GMD',
    'GNF',
    'GTQ',
    'GYD',
    'HKD',
    'HNL',
    'HRK',
    'HTG',
    'HUF',
    'IDR',
    'ILS',
    'IMP',
    'INR',
    'IQD',
    'IRR',
    'ISK',
    'JEP',
    'JMD',
    'JOD',
    'JPY',
    'KES',
    'KGS',
    'KHR',
    'KMF',
    'KPW',
    'KRW',
    'KWD',
    'KYD',
    'KZT',
    'LAK',
    'LBP',
    'LKR',
    'LRD',
    'LSL',
    'LTL',
    'LVL',
    'LYD',
    'MAD',
    'MDL',
    'MGA',
    'MKD',
    'MMK',
    'MNT',
    'MOP',
    'MRO',
    'MUR',
    'MVR',
    'MWK',
    'MXN',
    'MYR',
    'MZN',
    'NAD',
    'NGN',
    'NIO',
    'NOK',
    'NPR',
    'NZD',
    'OMR',
    'PAB',
    'PEN',
    'PGK',
    'PHP',
    'PKR',
    'PLN',
    'PYG',
    'QAR',
    'RON',
    'RSD',
    'RUB',
    'RWF',
    'SAR',
    'SBD',
    'SCR',
    'SDG',
    'SEK',
    'SGD',
    'SHP',
    'SLL',
    'SOS',
    'SRD',
    'STD',
    'SVC',
    'SYP',
    'SZL',
    'THB',
    'TJS',
    'TMT',
    'TND',
    'TOP',
    'TRY',
    'TTD',
    'TWD',
    'TZS',
    'UAH',
    'UGX',
    'USD',
    'UYU',
    'UZS',
    'VEF',
    'VND',
    'VUV',
    'WST',
    'XAF',
    'XAG',
    'XAU',
    'XCD',
    'XDR',
    'XOF',
    'XPF',
    'YER',
    'ZAR',
    'ZMK',
    'ZMW',
    'ZWL'
];
// Símbolos soportados por la API, ordenados alfabéticamente.
export const SYMBOLS_ORDENADO = [
    'AED',
    'ARS',
    'AUD',
    'BGN',
    'BRL',
    'BSD',
    'CAD',
    'CHF',
    'CLP',
    'CNY',
    'COP',
    'CZK',
    'DKK',
    'DOP',
    'EGP',
    'EUR',
    'FJD',
    'GBP',
    'GTQ',
    'HKD',
    'HRK',
    'HUF',
    'IDR',
    'ILS',
    'INR',
    'ISK',
    'JPY',
    'KRW',
    'KZT',
    'MXN',
    'MYR',
    'NOK',
    'NZD',
    'PAB',
    'PEN',
    'PHP',
    'PKR',
    'PLN',
    'PYG',
    'RON',
    'RUB',
    'SAR',
    'SEK',
    'SGD',
    'THB',
    'TRY',
    'TWD',
    'UAH',
    'USD',
    'UYU',
    'ZAR'
];
// Símbolos procesados y ordenados por preferencias.
export const SYMBOLS = [
    { simbolo: 'USD', nombre: 'United States Dollar', nombrePais: 'United States', flag: 'flag-icon flag-icon-us' },
    { simbolo: 'EUR', nombre: 'Euro', nombrePais: 'EU', flag: 'flag-icon flag-icon-eu' },
    { simbolo: 'GBP', nombre: 'Pound Sterling', nombrePais: 'United Kingdom', flag: 'flag-icon flag-icon-gb' },
    { simbolo: 'ARS', nombre: 'Argentine Peso', nombrePais: 'Argentina', flag: 'flag-icon flag-icon-ar' },
    { simbolo: 'AED', nombre: 'UAE Dirham', nombrePais: 'United Arab Emirates', flag: 'flag-icon flag-icon-ae' },
    { simbolo: 'AUD', nombre: 'Australian Dollar', nombrePais: 'Australia', flag: 'flag-icon flag-icon-au' },
    { simbolo: 'BGN', nombre: 'Bulgarian Lev', nombrePais: 'Bulgaria', flag: 'flag-icon flag-icon-bg' },
    { simbolo: 'BRL', nombre: 'Brazilian Real', nombrePais: 'Brazil', flag: 'flag-icon flag-icon-br' },
    { simbolo: 'BSD', nombre: 'Bahamian Dollar', nombrePais: 'Bahamas', flag: 'flag-icon flag-icon-bs' },
    { simbolo: 'CAD', nombre: 'Canadian Dollar', nombrePais: 'Canada', flag: 'flag-icon flag-icon-ca' },
    { simbolo: 'CHF', nombre: 'Swiss Franc', nombrePais: 'Switzerland', flag: 'flag-icon flag-icon-ch' },
    { simbolo: 'CLP', nombre: 'Chilean Peso', nombrePais: 'Chile', flag: 'flag-icon flag-icon-cl' },
    { simbolo: 'CNY', nombre: 'Chinese Renminbi', nombrePais: 'China', flag: 'flag-icon flag-icon-cn' },
    { simbolo: 'COP', nombre: 'Colombian Peso', nombrePais: 'Colombia', flag: 'flag-icon flag-icon-co' },
    { simbolo: 'CZK', nombre: 'Czech Koruna', nombrePais: 'Czech Republic', flag: 'flag-icon flag-icon-cz' },
    { simbolo: 'DKK', nombre: 'Danish Krone', nombrePais: 'Denmark', flag: 'flag-icon flag-icon-dk' },
    { simbolo: 'DOP', nombre: 'Dominican Peso', nombrePais: 'Dominican Republic', flag: 'flag-icon flag-icon-dm' },
    { simbolo: 'EGP', nombre: 'Egyptian Pound', nombrePais: 'Egypt', flag: 'flag-icon flag-icon-eg' },
    { simbolo: 'FJD', nombre: 'Fiji Dollar', nombrePais: 'Fiji', flag: 'flag-icon flag-icon-fj' },
    { simbolo: 'GTQ', nombre: 'Guatemalan Quetzal', nombrePais: 'Guatemala', flag: 'flag-icon flag-icon-gt' },
    { simbolo: 'HKD', nombre: 'Hong Kong Dollar', nombrePais: 'Hong Kong', flag: 'flag-icon flag-icon-hk' },
    { simbolo: 'HRK', nombre: 'Croatian Kuna', nombrePais: 'Croatia', flag: 'flag-icon flag-icon-hr' },
    { simbolo: 'HUF', nombre: 'Hungarian Forint', nombrePais: 'Hungary', flag: 'flag-icon flag-icon-hu' },
    { simbolo: 'IDR', nombre: 'Indonesian Rupiah', nombrePais: 'Indonesia', flag: 'flag-icon flag-icon-id' },
    { simbolo: 'ILS', nombre: 'Israeli New Shekel', nombrePais: 'Israel', flag: 'flag-icon flag-icon-il' },
    { simbolo: 'INR', nombre: 'Indian Rupee', nombrePais: 'India', flag: 'flag-icon flag-icon-in' },
    { simbolo: 'ISK', nombre: 'Icelandic Krona', nombrePais: 'Iceland', flag: 'flag-icon flag-icon-is' },
    { simbolo: 'JPY', nombre: 'Japanese Yen', nombrePais: 'Japan', flag: 'flag-icon flag-icon-jp' },
    { simbolo: 'KRW', nombre: 'South Korean Won', nombrePais: 'South Korea', flag: 'flag-icon flag-icon-kr' },
    { simbolo: 'KZT', nombre: 'Kazakhstani Tenge', nombrePais: 'Kazakhstan', flag: 'flag-icon flag-icon-kz' },
    { simbolo: 'MXN', nombre: 'Mexican Peso', nombrePais: 'Mexico', flag: 'flag-icon flag-icon-mx' },
    { simbolo: 'MYR', nombre: 'Malaysian Ringgit', nombrePais: 'Malaysia', flag: 'flag-icon flag-icon-my' },
    { simbolo: 'NOK', nombre: 'Norwegian Krone', nombrePais: 'Norway', flag: 'flag-icon flag-icon-no' },
    { simbolo: 'NZD', nombre: 'New Zealand Dollar', nombrePais: 'New Zealand', flag: 'flag-icon flag-icon-nz' },
    { simbolo: 'PAB', nombre: 'Panamanian Balboa', nombrePais: 'Panama', flag: 'flag-icon flag-icon-pa' },
    { simbolo: 'PEN', nombre: 'Peruvian Sol', nombrePais: 'Peru', flag: 'flag-icon flag-icon-pe' },
    { simbolo: 'PHP', nombre: 'Philippine Peso', nombrePais: 'Philippines', flag: 'flag-icon flag-icon-ph' },
    { simbolo: 'PKR', nombre: 'Pakistani Rupee', nombrePais: 'Pakistan', flag: 'flag-icon flag-icon-pk' },
    { simbolo: 'PLN', nombre: 'Polish Zloty', nombrePais: 'Poland', flag: 'flag-icon flag-icon-pl' },
    { simbolo: 'PYG', nombre: 'Paraguayan Guarani', nombrePais: 'Paraguay', flag: 'flag-icon flag-icon-py' },
    { simbolo: 'RON', nombre: 'Romanian Leu', nombrePais: 'Romania', flag: 'flag-icon flag-icon-ro' },
    { simbolo: 'RUB', nombre: 'Russian Ruble', nombrePais: 'Russia', flag: 'flag-icon flag-icon-ru' },
    { simbolo: 'SAR', nombre: 'Saudi Riyal', nombrePais: 'Saudi Arabia', flag: 'flag-icon flag-icon-sa' },
    { simbolo: 'SEK', nombre: 'Swedish Krona', nombrePais: 'Sweden', flag: 'flag-icon flag-icon-se' },
    { simbolo: 'SGD', nombre: 'Singapore Dollar', nombrePais: 'Singapore', flag: 'flag-icon flag-icon-sg' },
    { simbolo: 'THB', nombre: 'Thai Baht', nombrePais: 'Thailand', flag: 'flag-icon flag-icon-th' },
    { simbolo: 'TRY', nombre: 'Turkish Lira', nombrePais: 'Turkey', flag: 'flag-icon flag-icon-tr' },
    { simbolo: 'TWD', nombre: 'New Taiwan Dollar', nombrePais: 'Taiwan', flag: 'flag-icon flag-icon-tw' },
    { simbolo: 'UAH', nombre: 'Ukrainian Hryvnia', nombrePais: 'Ukraine', flag: 'flag-icon flag-icon-ua' },
    { simbolo: 'UYU', nombre: 'Uruguayan Peso', nombrePais: 'Uruguay', flag: 'flag-icon flag-icon-uy' },
    { simbolo: 'ZAR', nombre: 'South African Rand', nombrePais: 'South Africa', flag: 'flag-icon flag-icon-za' }
];
